2016-09-05 11:47:24 Warning: Warning (2): require_once(C:\xampp\htdocs\cake\vendor\adodb-time.inc.php): failed to open stream: No such file or directory in [C:\xampp\htdocs\cake\src\Controller\MapController.php, line 18]
Request URL: /cake/map
Referer URL: http://localhost/cake/info
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\MapController::index() - APP/Controller\MapController.php, line 18
App\Controller\MapController::index() - APP/Controller\MapController.php, line 18
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-05 12:14:02 Error: [Cake\View\Exception\MissingLayoutException] Layout file "Layout\error.ctp" is missing.
#0 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\View\View.php(620): Cake\View\View->_getLayoutFileName('error')
#1 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\View\View.php(596): Cake\View\View->renderLayout('', 'error')
#2 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(366): Cake\View\View->render('error500', 'error')
#3 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(345): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#4 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(194): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#5 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(70): Cake\Error\ExceptionRenderer->render()
#6 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(54): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(PDOException), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Server.php(82): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#10 C:\xampp\htdocs\History-web\webroot\index.php(37): Cake\Http\Server->run()
#11 {main}
2016-09-05 12:14:06 Error: [Cake\View\Exception\MissingLayoutException] Layout file "Layout\error.ctp" is missing.
#0 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\View\View.php(620): Cake\View\View->_getLayoutFileName('error')
#1 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\View\View.php(596): Cake\View\View->renderLayout('', 'error')
#2 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(366): Cake\View\View->render('error500', 'error')
#3 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(345): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#4 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(194): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#5 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(70): Cake\Error\ExceptionRenderer->render()
#6 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(54): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(Cake\View\Exception\MissingLayoutException), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Server.php(82): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#10 C:\xampp\htdocs\History-web\webroot\index.php(37): Cake\Http\Server->run()
#11 {main}
2016-09-05 13:42:48 Error: Fatal Error (1): Call to undefined method App\View\AppView::loadModel() in [C:\xampp\htdocs\History-web\src\Template\Users\registration.ctp, line 4]
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/articles/new-article
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-05 13:42:48 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::loadModel()
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/articles/new-article
Stack Trace:
#0 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 4)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-05 13:51:16 Warning: Warning (4096): Object of class Cake\Database\Connection could not be converted to string in [C:\xampp\htdocs\History-web\src\Controller\UsersController.php, line 48]
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/articles/new-article
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::registration() - APP/Controller\UsersController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-05 13:51:17 Warning: Headers already sent in C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-05 13:51:17 Error: [RuntimeException] Unable to emit response; headers already sent
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/articles/new-article
Stack Trace:
#0 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Server.php(107): Zend\Diactoros\Response\SapiStreamEmitter->emit(Object(Zend\Diactoros\Response))
#1 C:\xampp\htdocs\History-web\webroot\index.php(37): Cake\Http\Server->emit(Object(Zend\Diactoros\Response))
#2 {main}


2016-09-05 13:51:23 Warning: Warning (4096): Object of class Cake\Database\Connection could not be converted to string in [C:\xampp\htdocs\History-web\src\Controller\UsersController.php, line 48]
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/users/registration
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::registration() - APP/Controller\UsersController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-05 13:51:23 Warning: Headers already sent in C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-05 13:51:23 Error: [RuntimeException] Unable to emit response; headers already sent
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/users/registration
Stack Trace:
#0 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Server.php(107): Zend\Diactoros\Response\SapiStreamEmitter->emit(Object(Zend\Diactoros\Response))
#1 C:\xampp\htdocs\History-web\webroot\index.php(37): Cake\Http\Server->emit(Object(Zend\Diactoros\Response))
#2 {main}


2016-09-05 13:51:43 Warning: Warning (4096): Object of class Cake\Database\Connection could not be converted to string in [C:\xampp\htdocs\History-web\src\Controller\UsersController.php, line 48]
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/users/registration
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::registration() - APP/Controller\UsersController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-05 13:51:43 Warning: Headers already sent in C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-05 13:51:43 Error: [RuntimeException] Unable to emit response; headers already sent
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/users/registration
Stack Trace:
#0 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Server.php(107): Zend\Diactoros\Response\SapiStreamEmitter->emit(Object(Zend\Diactoros\Response))
#1 C:\xampp\htdocs\History-web\webroot\index.php(37): Cake\Http\Server->emit(Object(Zend\Diactoros\Response))
#2 {main}


2016-09-05 13:57:50 Warning: Warning (4096): Object of class DebugKit\Database\Log\DebugLog could not be converted to string in [C:\xampp\htdocs\History-web\src\Controller\UsersController.php, line 48]
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/users/registration
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::registration() - APP/Controller\UsersController.php, line 48
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-05 13:57:50 Warning: Headers already sent in C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-05 13:57:50 Error: [RuntimeException] Unable to emit response; headers already sent
Request URL: /History-web/users/registration
Referer URL: http://localhost/History-web/users/registration
Stack Trace:
#0 C:\xampp\htdocs\History-web\vendor\cakephp\cakephp\src\Http\Server.php(107): Zend\Diactoros\Response\SapiStreamEmitter->emit(Object(Zend\Diactoros\Response))
#1 C:\xampp\htdocs\History-web\webroot\index.php(37): Cake\Http\Server->emit(Object(Zend\Diactoros\Response))
#2 {main}


